### ISSUE TITLE
Chapter12   Stack.hs   error

### ISSUE THREAD

**Issue by boboyada** [HaskellZhangSong/Introduction_to_Haskell#11]
环境ubuntu kylin  linux 16.10 ,ghci 7.10.3
装载Stack.hs时出现了错误，可能是版本变化?
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
Prelude> :l Stack.hs
[1 of 1] Compiling Main             ( Stack.hs, interpreted )

Stack.hs:5:17: parse error on input ‘:’
Failed, modules loaded: none.

**Comment by eccstartup** [comment]
`\x:xs` 要改成 `\(x:xs)` ？

**Comment by boboyada** [comment]
OK
